# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
  app.account.service:
    class: AppBundle\Service\AccountService
    arguments: ['@doctrine.orm.entity_manager']
  app.client.service:
    class: AppBundle\Service\ClientService
    arguments: ['@doctrine.orm.entity_manager']
